builders:
  auto_intl:
    import: "package:intl_generator/intl_builder.dart"
    builder_factories: ["autoIntlBuilder"]
    build_extensions: {".dart": [".intl.dart"]}
    auto_apply: "root_package"
    defaults: {"generate_for": {"include": ["lib/strings.dart"]}}
    build_to: source