name: intl_generator
description: Code generation for string definition files using the Dart intl package
version: 0.1.0
author:
homepage:

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  source_gen:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1


# The following section is specific to Flutter.
flutter:

