name: intl_generator
description: Code generation for string definition files using the Dart intl package
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  source_gen:
  build_runner: 0.8.8

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

